---
detectors:
  IrresponsibleModule:
    enabled: false
  FeatureEnvy:
    exclude:
      - "EventsController#save_previous_generated_errors"
  NestedIterators:
    exclude:
      - "Event#self.to_csv"
  ControlParameter:
    exclude:
      - "EventReminderJob#perform"
  TooManyMethods:
    max_methods: 17
  TooManyStatements:
    max_statements: 6

directories:
  "app/controllers":
    InstanceVariableAssumption:
      enabled: false
    NestedIterators:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
    NestedIterators:
      enabled: false
  "app/jobs":
    UtilityFunction:
      enabled: false
  "app/helpers":
    UtilityFunction:
      enabled: false

exclude_paths:
  - "bin"
  - "config"
  - "db"
