---
detectors:
  IrresponsibleModule:
    enabled: false
  FeatureEnvy:
    exclude:
      - "EventsController#save_previous_generated_errors"
  TooManyMethods:
    max_methods: 16
  TooManyStatements:
    max_statements: 6

directories:
  "app/controllers":
    InstanceVariableAssumption:
      enabled: false
    NestedIterators:
      enabled: false
  "app/helpers":
    UtilityFunction:
      enabled: false
      
exclude_paths:
  - "bin"
  - "config"
  - "db"